### ISSUE TITLE
Please fix this issue in next update

### ISSUE THREAD

**Issue by nileshsoni97** [dgofman/nats_client#2]
` if (subs != null && subs[sid] != null) {     // add this check in your transport.dart file to avoid crash
              Subscription s = subs[sid]!;
              if (totalBytes > 0 && s.callback is SubCallback) {
                if (start + totalBytes < data.length) {
                  s.callback!(
                      Result(data.sublist(start, start + totalBytes), s, subject));
                } else {
                  _openSubscription = OpenSubscription(s, subject, totalBytes);
                  if (data.length > start) {
                    _openSubscription!.buffer.addAll(data.sublist(start));
                  }
                }
              }
            }   // add this check in your transport.dart file to avoid crash`

Here is error details : 

    `[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
    E/flutter ( 8983): #0      WsTransport.parse (package:nats_client/natslite/transport.dart:374:37)
    E/flutter ( 8983): #1      WsTransport.connect.<anonymous closure> (package:nats_client/natslite/transport.dart:200:15)
    E/flutter ( 8983): #2      WsTransport.connect.<anonymous closure> (package:nats_client/natslite/transport.dart:187:44)`

**Comment by dgofman** [comment]
@nileshsoni97 Please can you open a Pull Request for merge?

**Comment by dgofman** [comment]
@nileshsoni97 Merged. Thanks!
