### ISSUE TITLE
Flutter 3.10.0 not work

### ISSUE THREAD

**Issue by tungvt80** [dgofman/nats_client#5]
Error (Xcode): ../../.pub-cache/hosted/pub.dev/nats_client-2.1.1/lib/natslite/transport.dart:331:13: Error: A 'continue' label must be on a loop or a switch member.

**Comment by dgofman** [comment]
@tungvt80 What version of the flutter are you using?
This issue was fixed in Dart in January.
https://github.com/dart-lang/sdk/commit/49c7d930425b695d577802121f83a0bc77b39ef3

**Comment by tungvt80** [comment]
I'm using new Flutter 3.10.0  buid false:
Error (Xcode): ../../.pub-cache/hosted/pub.dev/nats_client-2.1.1/lib/natslite/transport.dart:331:13: Error: A 'continue' label must be on a loop or a switch member.
==
I'm fix: fluter downgrade   Flutter 3.7.12 is Work

**Comment by dgofman** [comment]
@tungvt80 I have installed 3.10.0 on my local machine however I am unable to launch the debugger in Android Studio. So I reverted to 3.7 as well.

flutter downgrade 3.7.12
flutter --version

**Comment by dgofman** [comment]
@tungvt80 

I published my changes https://pub.dev/packages/nats_client/versions/2.2.0

**Comment by dgofman** [comment]
Supports Dart 3.0.0
