### ISSUE TITLE
Cannot connect to ws://myServer on macOS Desktop but only on web

### ISSUE THREAD

**Issue by MichaelVoelkel** [dgofman/nats_client#6]
Hi,

text says it. So it all works fine when I start project for web.

However, if I start it for macOS Desktop (no code change) I get connecting to NATS failed: WebSocketChannelException: SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = my-server.com, port = 4997

How then?

**Comment by MichaelVoelkel** [comment]
By the way, if I try a normal NATS port without WS like "nats://my-server.com:4222" it will also not work

**Comment by dgofman** [comment]
Did you follow the setup script?  https://github.com/dgofman/nats_client/blob/master/test/setup.sh

**Comment by MichaelVoelkel** [comment]
That's not the point. My NATS server works fully and is in use with many languages and clients. My point is: _If_ the token is wrong (I manipulated it on purpose), then the error handling is hard to accomplish

**Comment by MichaelVoelkel** [comment]
Roughly yes, but please understand that I will not create my NATS setup based on the 3rd party readme. My setup works well with clients from C, JS, and Go, just not with your tool, but I can give it another try and provide more information later!

**Comment by dgofman** [comment]
To execute your current setup successfully, it is very important to have a comprehensive understanding of the features and limitations of the NATS protocol. My approach involves initially assessing the components that are functioning correctly. Subsequently, you systematically update the local system, incrementally transitioning from a working environment to one that is not functional. This method allows you to pinpoint any issues within the current settings and address them effectively.

**Comment by MichaelVoelkel** [comment]
Yeah, minimal viable example, that is true! How else could you have a chance to reproduce? I am on something else but will come back later with something more helpful. Thanks for your prompt responses!

**Comment by MichaelVoelkel** [comment]
Ok, I tried it now after some while AND it works. Maybe because I added re-attempt or something. But I can definitely close it for now! Sorry for the waste of time
