### ISSUE TITLE
When internet disconnect its not auto re-connect and crash.

### ISSUE THREAD

**Issue by nileshsoni97** [dgofman/nats_client#7]
Here is the logs :

`E/flutter ( 4514): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: WebSocketChannelException: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address =  myServerIP, port = 4222
E/flutter ( 4514): #0      WsTransport.connect.<anonymous closure> (package:nats_client/natslite/transport.dart:205:31)
E/flutter ( 4514): #1      _RootZone.runUnary (dart:async/zone.dart:1661:54)
E/flutter ( 4514): #2      _FutureListener.handleError (dart:async/future_impl.dart:174:22)
E/flutter ( 4514): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
E/flutter ( 4514): #4      Future._propagateToListeners (dart:async/future_impl.dart:873:13)
E/flutter ( 4514): #5      Future._completeError (dart:async/future_impl.dart:649:5)
E/flutter ( 4514): #6      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:739:7)
E/flutter ( 4514): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 4514): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)`

**Comment by dgofman** [comment]
Please let me know if you are still running this issue.
